export interface DSAQuestion {
  id: string;
  title: string;
  completed: boolean;
  level: number | string;
}

export interface DSAPhase {
  id: string;
  title: string;
  description: string;
  questions: DSAQuestion[];
}

export const DEEPAYAN_SHEET: DSAPhase[] = [
  {
    id: 'phase-1',
    title: 'Phase 1 - Conditional Thinking',
    description: 'Goal: Understand how to make decisions using conditions.',
    questions: [
      // Level 1
      { id: 'p1-l1-1', title: '1. Take a number and print whether it’s positive, negative, or zero.', level: 1, completed: false },
      { id: 'p1-l1-2', title: '2. Check if a number is even or odd.', level: 1, completed: false },
      { id: 'p1-l1-3', title: '3. Check if a number is divisible by 5.', level: 1, completed: false },
      { id: 'p1-l1-4', title: '4. Check if a number is divisible by both 3 and 5.', level: 1, completed: false },
      { id: 'p1-l1-5', title: '5. Check if a given year is a leap year.', level: 1, completed: false },
      { id: 'p1-l1-6', title: '6. Take two numbers and print the larger one.', level: 1, completed: false },
      { id: 'p1-l1-7', title: '7. Take three numbers and print the largest.', level: 1, completed: false },
      { id: 'p1-l1-8', title: '8. Take a temperature value and print “Cold”, “Warm”, or “Hot” using range conditions.', level: 1, completed: false },
      { id: 'p1-l1-9', title: '9. Take a character and check if it’s a vowel or consonant.', level: 1, completed: false },
      { id: 'p1-l1-10', title: '10. Take a character and check whether it’s uppercase, lowercase, a digit, or a special character.', level: 1, completed: false },
      // Level 2
      { id: 'p1-l2-1', title: '1. Take three sides and check if they form a valid triangle.', level: 2, completed: false },
      { id: 'p1-l2-2', title: '2. If the sides form a valid triangle, determine whether it is equilateral, isosceles, or scalene.', level: 2, completed: false },
      { id: 'p1-l2-3', title: '3. Take marks (0–100) and print the corresponding grade (A/B/C/D/F).', level: 2, completed: false },
      { id: 'p1-l2-4', title: '4. Check if one of two given numbers is a multiple of the other.', level: 2, completed: false },
      { id: 'p1-l2-5', title: '5. Take the hour of the day (0–23) and print “Good Morning”, “Good Afternoon”, “Good Evening”, or “Good Night”.', level: 2, completed: false },
      { id: 'p1-l2-6', title: '6. Check voting eligibility for a given age (18+).', level: 2, completed: false },
      { id: 'p1-l2-7', title: '7. Take two numbers and determine whether both are even, both are odd, or one is even and one is odd.', level: 2, completed: false },
      { id: 'p1-l2-8', title: '8. Take an alphabet character and check if it lies between ‘a’ and ‘m’ or ‘n’ and ‘z’.', level: 2, completed: false },
      { id: 'p1-l2-9', title: '9. Take a day number (1–7) and print the corresponding day name.', level: 2, completed: false },
      { id: 'p1-l2-10', title: '10. Take a month number (1–12) and print the number of days in that month (ignore leap years).', level: 2, completed: false },
      // Level 3
      { id: 'p1-l3-1', title: '1. Take a 3-digit number and check if all digits are distinct.', level: 3, completed: false },
      { id: 'p1-l3-2', title: '2. Take a 3-digit number and determine if the middle digit is the largest, smallest, or neither.', level: 3, completed: false },
      { id: 'p1-l3-3', title: '3. Take a 4-digit number and check if the first and last digits are equal.', level: 3, completed: false },
      { id: 'p1-l3-4', title: '4. Check whether a given integer is single-digit, double-digit, or multi-digit.', level: 3, completed: false },
      { id: 'p1-l3-5', title: '5. Check if a number is a multiple of 7 or ends with 7.', level: 3, completed: false },
      { id: 'p1-l3-6', title: '6. Take coordinates (x, y) and determine which quadrant the point lies in.', level: 3, completed: false },
      { id: 'p1-l3-7', title: '7. Check if an amount can be evenly divided into 2000, 500, and 100 currency notes.', level: 3, completed: false },
      { id: 'p1-l3-8', title: '8. Check if a number lies within the range [100, 999].', level: 3, completed: false },
      { id: 'p1-l3-9', title: '9. Take two angles of a triangle and compute the third angle.', level: 3, completed: false },
      { id: 'p1-l3-10', title: '10. Check whether a number is a perfect square (without using the square root function).', level: 3, completed: false },
      // Level 4
      { id: 'p1-l4-1', title: '1. Take a character and check if it is a letter, a digit, or neither.', level: 4, completed: false },
      { id: 'p1-l4-2', title: '2. Take a number and print “Fizz” if divisible by 3, “Buzz” if divisible by 5, and “FizzBuzz” if divisible by both.', level: 4, completed: false },
      { id: 'p1-l4-3', title: '3. Take three numbers and print the median value (neither maximum nor minimum).', level: 4, completed: false },
      { id: 'p1-l4-4', title: '4. Take 24-hour time (hours and minutes) and print whether it is AM or PM.', level: 4, completed: false },
      { id: 'p1-l4-5', title: '5. Take income and age, and check if eligible for tax (age > 18 and income > 5 L).', level: 4, completed: false },
      { id: 'p1-l4-6', title: '6. Take two numbers and check if both are positive and their sum is less than 100.', level: 4, completed: false },
      { id: 'p1-l4-7', title: '7. Take a single digit (0–9) and print its word form (“Zero” to “Nine”).', level: 4, completed: false },
      { id: 'p1-l4-8', title: '8. Take a weekday number (1–7) and determine if it is a weekday or weekend.', level: 4, completed: false },
      { id: 'p1-l4-9', title: '9. Take electricity units consumed and calculate the bill as per slabs (using if-else).', level: 4, completed: false },
      { id: 'p1-l4-10', title: '10. Take a password string and check basic rules (length ≥ 8 and contains at least one digit).', level: 4, completed: false },
      // Level 5
      { id: 'p1-l5-1', title: '1. Take coordinates (x, y) and check if the point lies on the X-axis, Y-axis, or at the origin.', level: 5, completed: false },
      { id: 'p1-l5-2', title: '2. Take three numbers and check if they can form a Pythagorean triplet.', level: 5, completed: false },
      { id: 'p1-l5-3', title: '3. Take day and month and check if it forms a valid calendar date (ignoring leap years).', level: 5, completed: false },
      { id: 'p1-l5-4', title: '4. Take time (hours and minutes) and print the smaller angle between the hour and minute hands.', level: 5, completed: false },
      { id: 'p1-l5-5', title: '5. Take three numbers and check if they are in arithmetic progression.', level: 5, completed: false },
      { id: 'p1-l5-6', title: '6. Take three numbers and check if they are in geometric progression.', level: 5, completed: false },
      { id: 'p1-l5-7', title: '7. Take a 3-digit number and check if the sum of the first and last digit equals the middle digit.', level: 5, completed: false },
      { id: 'p1-l5-8', title: '8. Take an integer (1–9999) and check if the sum of its digits is greater than the product of its digits.', level: 5, completed: false },
      { id: 'p1-l5-9', title: '9. Take two dates (day and month) and determine which one comes first in the calendar.', level: 5, completed: false },
      { id: 'p1-l5-10', title: '10. Take a year and print the corresponding century (e.g., “19th century”, “20th century”)', level: 5, completed: false },
    ]
  },
  {
    id: 'phase-2',
    title: 'Phase 2 - Looping & Patterns',
    description: 'Goal: Master loops, iteration, and dry-run thinking.',
    questions: [
      // Level 1
      { id: 'p2-l1-1', title: '1. Print numbers from 1 to 10.', level: 1, completed: false },
      { id: 'p2-l1-2', title: '2. Print all even numbers between 1 and 100.', level: 1, completed: false },
      { id: 'p2-l1-3', title: '3. Print all odd numbers between 1 and 100.', level: 1, completed: false },
      { id: 'p2-l1-4', title: '4. Print numbers from 10 down to 1.', level: 1, completed: false },
      { id: 'p2-l1-5', title: '5. Print the table of a given number (n × 1 to n × 10).', level: 1, completed: false },
      { id: 'p2-l1-6', title: '6. Print the sum of first n natural numbers.', level: 1, completed: false },
      { id: 'p2-l1-7', title: '7. Print the sum of all even numbers up to n.', level: 1, completed: false },
      { id: 'p2-l1-8', title: '8. Print the sum of all odd numbers up to n.', level: 1, completed: false },
      { id: 'p2-l1-9', title: '9. Print the factorial of a given number.', level: 1, completed: false },
      { id: 'p2-l1-10', title: '10. Print the product of digits of a given number.', level: 1, completed: false },
      // Level 2
      { id: 'p2-l2-1', title: '1. Count the number of digits in a given number.', level: 2, completed: false },
      { id: 'p2-l2-2', title: '2. Print the reverse of a given number.', level: 2, completed: false },
      { id: 'p2-l2-3', title: '3. Check if a number is a palindrome.', level: 2, completed: false },
      { id: 'p2-l2-4', title: '4. Find the sum of digits of a number.', level: 2, completed: false },
      { id: 'p2-l2-5', title: '5. Check if a number is an Armstrong number.', level: 2, completed: false },
      { id: 'p2-l2-6', title: '6. Check if a number is a perfect number.', level: 2, completed: false },
      { id: 'p2-l2-7', title: '7. Print all prime numbers between 1 and 100.', level: 2, completed: false },
      { id: 'p2-l2-8', title: '8. Check if a number is prime or not.', level: 2, completed: false },
      { id: 'p2-l2-9', title: '9. Print Fibonacci series up to n terms.', level: 2, completed: false },
      { id: 'p2-l2-10', title: '10. Print sum of first n terms of Fibonacci series.', level: 2, completed: false },
      // Level 3
      { id: 'p2-l3-1', title: '1. Print the squares of numbers from 1 to n.', level: 3, completed: false },
      { id: 'p2-l3-2', title: '2. Print cubes of numbers from 1 to n.', level: 3, completed: false },
      { id: 'p2-l3-3', title: '3. Print all numbers between a and b divisible by 7.', level: 3, completed: false },
      { id: 'p2-l3-4', title: '4. Find HCF (GCD) of two numbers using loops.', level: 3, completed: false },
      { id: 'p2-l3-5', title: '5. Find LCM of two numbers using loops.', level: 3, completed: false },
      { id: 'p2-l3-6', title: '6. Print all factors of a given number.', level: 3, completed: false },
      { id: 'p2-l3-7', title: '7. Find the sum of all factors of a number.', level: 3, completed: false },
      { id: 'p2-l3-8', title: '8. Check if a number is a strong number (sum of factorials of digits = number).', level: 3, completed: false },
      { id: 'p2-l3-9', title: '9. Print first n terms of an arithmetic progression (a, d).', level: 3, completed: false },
      { id: 'p2-l3-10', title: '10. Print first n terms of a geometric progression (a, r).', level: 3, completed: false },
      // Level 4
      { id: 'p2-l4-1', title: '1. Print all prime factors of a given number.', level: 4, completed: false },
      { id: 'p2-l4-2', title: '2. Print all Armstrong numbers between 1 and 1000.', level: 4, completed: false },
      { id: 'p2-l4-3', title: '3. Print all Perfect numbers between 1 and 1000.', level: 4, completed: false },
      { id: 'p2-l4-4', title: '4. Print the first n prime numbers.', level: 4, completed: false },
      { id: 'p2-l4-5', title: '5. Find the sum of all prime numbers between 1 and n.', level: 4, completed: false },
      { id: 'p2-l4-6', title: '6. Print Pascal’s triangle up to n rows.', level: 4, completed: false },
      { id: 'p2-l4-7', title: '7. Print Floyd’s triangle up to n rows.', level: 4, completed: false },
      { id: 'p2-l4-8', title: '8. Check if a number is an Automorphic number.', level: 4, completed: false },
      { id: 'p2-l4-9', title: '9. Check if a number is a Harshad (Niven) number.', level: 4, completed: false },
      { id: 'p2-l4-10', title: '10. Find the square root of a number using the Babylonian method (loop).', level: 4, completed: false },
      // Level 5
      { id: 'p2-l5-1', title: '1. Print all numbers whose sum of digits is even (1–100).', level: 5, completed: false },
      { id: 'p2-l5-2', title: '2. Count how many numbers between 1–500 are divisible by 7 but not by 5.', level: 5, completed: false },
      { id: 'p2-l5-3', title: '3. Print all numbers that are palindromes between 1–500.', level: 5, completed: false },
      { id: 'p2-l5-4', title: '4. Print numbers between 1–100 whose digits add up to a multiple of 3.', level: 5, completed: false },
      { id: 'p2-l5-5', title: '5. Find the smallest and largest digit in a given number.', level: 5, completed: false },
      { id: 'p2-l5-6', title: '6. Print all numbers from 1–n whose binary representation has an even number of 1s.', level: 5, completed: false },
      { id: 'p2-l5-7', title: '7. Print a pattern where each row i prints i*i.', level: 5, completed: false },
      { id: 'p2-l5-8', title: '8. Print factorial of each number from 1 to n.', level: 5, completed: false },
      { id: 'p2-l5-9', title: '9. Print the sum of all odd digits and even digits separately in a number.', level: 5, completed: false },
      { id: 'p2-l5-10', title: '10. Take 5 numbers as input. If the user enters 0, skip it using continue. At the end, print the sum of all non-zero numbers entered.', level: 5, completed: false },
    ]
  },
  {
    id: 'phase-3',
    title: 'Phase 3 - Recursion',
    description: 'Goal: Develop logical decomposition and base-condition thinking.',
    questions: [
      // Level 1
      { id: 'p3-l1-1', title: '1. Print numbers from 1 to n using recursion.', level: 1, completed: false },
      { id: 'p3-l1-2', title: '2. Print numbers from n down to 1 using recursion.', level: 1, completed: false },
      { id: 'p3-l1-3', title: '3. Print only even numbers from 1 to n recursively.', level: 1, completed: false },
      { id: 'p3-l1-4', title: '4. Print only odd numbers from 1 to n recursively.', level: 1, completed: false },
      { id: 'p3-l1-5', title: '5. Print sum of first n natural numbers recursively.', level: 1, completed: false },
      { id: 'p3-l1-6', title: '6. Print factorial of a number recursively.', level: 1, completed: false },
      { id: 'p3-l1-7', title: '7. Calculate power of a number (xⁿ) using recursion.', level: 1, completed: false },
      { id: 'p3-l1-8', title: '8. Find nth Fibonacci number recursively.', level: 1, completed: false },
      { id: 'p3-l1-9', title: '9. Print Fibonacci series up to n terms recursively.', level: 1, completed: false },
      { id: 'p3-l1-10', title: '10. Find sum of digits of a number recursively.', level: 1, completed: false },
      // Level 2
      { id: 'p3-l2-1', title: '1. Count the number of digits in a number recursively.', level: 2, completed: false },
      { id: 'p3-l2-2', title: '2. Reverse a number recursively.', level: 2, completed: false },
      { id: 'p3-l2-3', title: '3. Check if a number is a palindrome using recursion.', level: 2, completed: false },
      { id: 'p3-l2-4', title: '4. Find product of digits of a number recursively.', level: 2, completed: false },
      { id: 'p3-l2-5', title: '5. Find GCD (HCF) of two numbers using Euclid’s algorithm recursively.', level: 2, completed: false },
      { id: 'p3-l2-6', title: '6. Convert a number to binary recursively.', level: 2, completed: false },
      { id: 'p3-l2-7', title: '7. Print digits of a number in words recursively (e.g., 123 → “one two three”).', level: 2, completed: false },
      { id: 'p3-l2-8', title: '8. Calculate the sum of first n even numbers recursively.', level: 2, completed: false },
      { id: 'p3-l2-9', title: '9. Calculate the sum of first n odd numbers recursively.', level: 2, completed: false },
      { id: 'p3-l2-10', title: '10. Find nCr (Combination formula) recursively using Pascal’s relation.', level: 2, completed: false },
      // Level 3
      { id: 'p3-l3-1', title: '1. Print a line of n stars recursively.', level: 3, completed: false },
      { id: 'p3-l3-2', title: '2. Print a square of stars recursively (n×n).', level: 3, completed: false },
      { id: 'p3-l3-3', title: '3. Print a triangle of stars recursively (top-down).', level: 3, completed: false },
      { id: 'p3-l3-4', title: '4. Print a triangle of stars recursively (bottom-up).', level: 3, completed: false },
      { id: 'p3-l3-5', title: '5. Print pattern of numbers recursively (1 to n each row).', level: 3, completed: false },
      { id: 'p3-l3-6', title: '6. Print reverse triangle pattern recursively.', level: 3, completed: false },
      { id: 'p3-l3-7', title: '7. Print multiplication table of n recursively.', level: 3, completed: false },
      { id: 'p3-l3-8', title: '8. Print numbers in increasing and decreasing order in same function.', level: 3, completed: false },
      { id: 'p3-l3-9', title: '9. Print sum of series 1 + 2 + 3 + ... + n recursively and display each step.', level: 3, completed: false },
      { id: 'p3-l3-10', title: '10. Print pattern of characters (A, AB, ABC, ...) recursively.', level: 3, completed: false },
      // Level 4
      { id: 'p3-l4-1', title: '1. Reverse a string using recursion.', level: 4, completed: false },
      { id: 'p3-l4-2', title: '2. Check if a string is palindrome using recursion.', level: 4, completed: false },
      { id: 'p3-l4-3', title: '3. Count vowels in a string recursively.', level: 4, completed: false },
      { id: 'p3-l4-4', title: '4. Remove all spaces from a string recursively.', level: 4, completed: false },
      { id: 'p3-l4-5', title: '5. Replace all occurrences of a character (say ‘a’ → ‘x’) recursively.', level: 4, completed: false },
      { id: 'p3-l4-6', title: '6. Remove all occurrences of a character from a string recursively.', level: 4, completed: false },
      { id: 'p3-l4-7', title: '7. Print all characters of a string one by one recursively.', level: 4, completed: false },
      { id: 'p3-l4-8', title: '8. Print the string in reverse order recursively (without using loops).', level: 4, completed: false },
      { id: 'p3-l4-9', title: '9. Convert a string to uppercase recursively.', level: 4, completed: false },
      { id: 'p3-l4-10', title: '10. Count consonants and vowels separately using recursion.', level: 4, completed: false },
      // Level 5
      { id: 'p3-l5-1', title: '1. Find the sum of an array recursively.', level: 5, completed: false },
      { id: 'p3-l5-2', title: '2. Find the maximum element in an array recursively.', level: 5, completed: false },
      { id: 'p3-l5-3', title: '3. Perform Binary Search using recursion.', level: 5, completed: false },
      { id: 'p3-l5-4', title: '4. Solve the Tower of Hanoi problem for n disks.', level: 5, completed: false },
      { id: 'p3-l5-5', title: '5. Generate all permutations of a string recursively.', level: 5, completed: false },
      { id: 'p3-l5-6', title: '6. Find the length of a string recursively.', level: 5, completed: false },
      { id: 'p3-l5-7', title: '7. Check if an array is sorted recursively.', level: 5, completed: false },
      { id: 'p3-l5-8', title: '8. Find the sum of first n squares recursively.', level: 5, completed: false },
      { id: 'p3-l5-9', title: '9. Convert a decimal number to hexadecimal recursively.', level: 5, completed: false },
      { id: 'p3-l5-10', title: '10. Count the number of occurrences of a character in a string recursively.', level: 5, completed: false },
    ]
  },
  {
    id: 'phase-4',
    title: 'Phase 4 - Basic Arrays',
    description: 'Goal: Build the ability to handle a collection logically.',
    questions: [
      // Level 1
      { id: 'p4-l1-1', title: '1. Input n and take n integers into an array; print them.', level: 1, completed: false },
      { id: 'p4-l1-2', title: '2. Find the sum of all elements in an array.', level: 1, completed: false },
      { id: 'p4-l1-3', title: '3. Find the average of array elements.', level: 1, completed: false },
      { id: 'p4-l1-4', title: '4. Find the maximum element in an array.', level: 1, completed: false },
      { id: 'p4-l1-5', title: '5. Find the minimum element in an array.', level: 1, completed: false },
      { id: 'p4-l1-6', title: '6. Count how many elements are positive, negative, or zero.', level: 1, completed: false },
      { id: 'p4-l1-7', title: '7. Count how many elements are even and odd.', level: 1, completed: false },
      { id: 'p4-l1-8', title: '8. Find the index of the maximum element.', level: 1, completed: false },
      { id: 'p4-l1-9', title: '9. Find the index of the minimum element.', level: 1, completed: false },
      { id: 'p4-l1-10', title: '10. Take n elements and print only those greater than a given value k.', level: 1, completed: false },
      // Level 2
      { id: 'p4-l2-1', title: '1. Input an element x — check if it exists in the array.', level: 2, completed: false },
      { id: 'p4-l2-2', title: '2. Count how many times a given element appears.', level: 2, completed: false },
      { id: 'p4-l2-3', title: '3. Find the first occurrence of a given number.', level: 2, completed: false },
      { id: 'p4-l2-4', title: '4. Find the last occurrence of a given number.', level: 2, completed: false },
      { id: 'p4-l2-5', title: '5. Check if all elements in an array are unique.', level: 2, completed: false },
      { id: 'p4-l2-6', title: '6. Find the sum of even elements only.', level: 2, completed: false },
      { id: 'p4-l2-7', title: '7. Find the sum of odd elements only.', level: 2, completed: false },
      { id: 'p4-l2-8', title: '8. Find the count of prime numbers in the array.', level: 2, completed: false },
      { id: 'p4-l2-9', title: '9. Count how many numbers are divisible by 3 and 5 both.', level: 2, completed: false },
      { id: 'p4-l2-10', title: '10. Count how many elements are perfect squares.', level: 2, completed: false },
      // Level 3
      { id: 'p4-l3-1', title: '1. Create a new array containing squares of all numbers.', level: 3, completed: false },
      { id: 'p4-l3-2', title: '2. Create a new array containing only even elements.', level: 3, completed: false },
      { id: 'p4-l3-3', title: '3. Replace every negative number with 0.', level: 3, completed: false },
      { id: 'p4-l3-4', title: '4. Replace all even numbers with 1 and all odd with 0.', level: 3, completed: false },
      { id: 'p4-l3-5', title: '5. Swap the first and last elements of the array.', level: 3, completed: false },
      { id: 'p4-l3-6', title: '6. Reverse an array (without using built-in reverse).', level: 3, completed: false },
      { id: 'p4-l3-7', title: '7. Rotate an array by one position to the left.', level: 3, completed: false },
      { id: 'p4-l3-8', title: '8. Rotate an array by one position to the right.', level: 3, completed: false },
      { id: 'p4-l3-9', title: '9. Swap alternate elements (1st ↔ 2nd, 3rd ↔ 4th, etc.).', level: 3, completed: false },
      { id: 'p4-l3-10', title: '10. Copy one array to another manually.', level: 3, completed: false },
      // Level 4
      { id: 'p4-l4-1', title: '1. Compare two arrays — check if they are equal (same elements & order).', level: 4, completed: false },
      { id: 'p4-l4-2', title: '2. Compare two arrays — check if they contain the same elements (ignore order).', level: 4, completed: false },
      { id: 'p4-l4-3', title: '3. Merge two arrays into a third array.', level: 4, completed: false },
      { id: 'p4-l4-4', title: '4. Find the common elements between two arrays.', level: 4, completed: false },
      { id: 'p4-l4-5', title: '5. Find elements that are in one array but not in the other.', level: 4, completed: false },
      { id: 'p4-l4-6', title: '6. Count how many elements are common between two arrays.', level: 4, completed: false },
      { id: 'p4-l4-7', title: '7. Find element-wise sum of two arrays (A[i] + B[i]).', level: 4, completed: false },
      { id: 'p4-l4-8', title: '8. Find element-wise product of two arrays.', level: 4, completed: false },
      { id: 'p4-l4-9', title: '9. Create a frequency array of numbers (count occurrence of each number).', level: 4, completed: false },
      { id: 'p4-l4-10', title: '10. Print all elements that appear more than once.', level: 4, completed: false },
      // Level 5
      { id: 'p4-l5-1', title: '1. Check if the array is sorted in ascending order.', level: 5, completed: false },
      { id: 'p4-l5-2', title: '2. Check if the array is sorted in descending order.', level: 5, completed: false },
      { id: 'p4-l5-3', title: '3. Find the second largest element in an array.', level: 5, completed: false },
      { id: 'p4-l5-4', title: '4. Find the second smallest element in an array.', level: 5, completed: false },
      { id: 'p4-l5-5', title: '5. Find the difference between the largest and smallest element.', level: 5, completed: false },
      { id: 'p4-l5-6', title: '6. Find the sum of all elements except the largest and smallest.', level: 5, completed: false },
      { id: 'p4-l5-7', title: '7. Count how many pairs of elements have a sum equal to a given number k.', level: 5, completed: false },
      { id: 'p4-l5-8', title: '8. Count how many elements are greater than the average of the array.', level: 5, completed: false },
      { id: 'p4-l5-9', title: '9. Print the frequency of each distinct element.', level: 5, completed: false },
      { id: 'p4-l5-10', title: '10. Print all unique elements (those that occur exactly once).', level: 5, completed: false },
    ]
  },
  {
    id: 'phase-5',
    title: 'Phase 5 - Strings',
    description: 'Goal: Basic logic building with strings.',
    questions: [
      // Category 1
      { id: 'p5-c1-1', title: '1. Take a string input and print its length.', level: 'C1', completed: false },
      { id: 'p5-c1-2', title: '2. Print the first and last character of a string.', level: 'C1', completed: false },
      { id: 'p5-c1-3', title: '3. Convert all characters of a string to uppercase.', level: 'C1', completed: false },
      { id: 'p5-c1-4', title: '4. Convert all characters of a string to lowercase.', level: 'C1', completed: false },
      { id: 'p5-c1-5', title: '5. Count how many characters (excluding spaces) are in the string.', level: 'C1', completed: false },
      { id: 'p5-c1-6', title: '6. Count how many words are in a sentence.', level: 'C1', completed: false },
      { id: 'p5-c1-7', title: '7. Take two strings and print them concatenated.', level: 'C1', completed: false },
      { id: 'p5-c1-8', title: '8. Compare two strings lexicographically (like dictionary order).', level: 'C1', completed: false },
      { id: 'p5-c1-9', title: '9. Print the ASCII value of each character in a string.', level: 'C1', completed: false },
      { id: 'p5-c1-10', title: '10. Check whether the string is empty or not.', level: 'C1', completed: false },
      // Category 2
      { id: 'p5-c2-1', title: '1. Count how many vowels and consonants are in a string.', level: 'C2', completed: false },
      { id: 'p5-c2-2', title: '2. Count the number of digits, letters, and special characters in a string.', level: 'C2', completed: false },
      { id: 'p5-c2-3', title: '3. Count how many uppercase and lowercase letters a string has.', level: 'C2', completed: false },
      { id: 'p5-c2-4', title: '4. Find the frequency of each character in a string (without using a map).', level: 'C2', completed: false },
      { id: 'p5-c2-5', title: '5. Count how many spaces are there in a sentence.', level: 'C2', completed: false },
      { id: 'p5-c2-6', title: '6. Count how many times a given character appears in a string.', level: 'C2', completed: false },
      { id: 'p5-c2-7', title: '7. Count how many alphabets are before ‘m’ and after ‘m’ in a given string.', level: 'C2', completed: false },
      { id: 'p5-c2-8', title: '8. Count how many substrings start and end with the same character (simple logic).', level: 'C2', completed: false },
      { id: 'p5-c2-9', title: '9. Print how many words start with a vowel in a sentence.', level: 'C2', completed: false },
      { id: 'p5-c2-10', title: '10. Count how many words end with ‘s’.', level: 'C2', completed: false },
      // Category 3
      { id: 'p5-c3-1', title: '1. Reverse a string without using built-in reverse.', level: 'C3', completed: false },
      { id: 'p5-c3-2', title: '2. Reverse each word in a sentence.', level: 'C3', completed: false },
      { id: 'p5-c3-3', title: '3. Reverse the order of words in a sentence.', level: 'C3', completed: false },
      { id: 'p5-c3-4', title: '4. Check whether a string is a palindrome.', level: 'C3', completed: false },
      { id: 'p5-c3-5', title: '5. Check if two strings are the reverse of each other.', level: 'C3', completed: false },
      { id: 'p5-c3-6', title: '6. Print the middle character(s) of a string.', level: 'C3', completed: false },
      { id: 'p5-c3-7', title: '7. Print the second half of the string in reverse.', level: 'C3', completed: false },
      { id: 'p5-c3-8', title: '8. Remove the first and last character and print the remaining string.', level: 'C3', completed: false },
      { id: 'p5-c3-9', title: '9. Reverse only characters, keeping digits in place.', level: 'C3', completed: false },
      { id: 'p5-c3-10', title: '10. Reverse string but skip spaces.', level: 'C3', completed: false },
      // Category 4
      { id: 'p5-c4-1', title: '1. Remove all vowels from a string.', level: 'C4', completed: false },
      { id: 'p5-c4-2', title: '2. Remove all spaces from a string.', level: 'C4', completed: false },
      { id: 'p5-c4-3', title: '3. Replace all vowels with ‘*’.', level: 'C4', completed: false },
      { id: 'p5-c4-4', title: '4. Replace all spaces with ‘_’.', level: 'C4', completed: false },
      { id: 'p5-c4-5', title: '5. Print the string after removing all digits.', level: 'C4', completed: false },
      { id: 'p5-c4-6', title: '6. Remove duplicate characters from a string.', level: 'C4', completed: false },
      { id: 'p5-c4-7', title: '7. Keep only the first occurrence of each character.', level: 'C4', completed: false },
      { id: 'p5-c4-8', title: '8. Remove consecutive duplicate characters (e.g., “aaabb” → “ab”).', level: 'C4', completed: false },
      { id: 'p5-c4-9', title: '9. Swap case: uppercase → lowercase and lowercase → uppercase.', level: 'C4', completed: false },
      { id: 'p5-c4-10', title: '10. Shift each character by 1 (e.g., “abc” → “bcd”).', level: 'C4', completed: false },
      // Category 5
      { id: 'p5-c5-1', title: '1. Print each word of a sentence on a new line.', level: 'C5', completed: false },
      { id: 'p5-c5-2', title: '2. Count how many words have even length.', level: 'C5', completed: false },
      { id: 'p5-c5-3', title: '3. Find the longest word in a sentence.', level: 'C5', completed: false },
      { id: 'p5-c5-4', title: '4. Find the shortest word in a sentence.', level: 'C5', completed: false },
      { id: 'p5-c5-5', title: '5. Swap first and last words in a sentence.', level: 'C5', completed: false },
      { id: 'p5-c5-6', title: '6. Print all words that start and end with the same letter.', level: 'C5', completed: false },
      { id: 'p5-c5-7', title: '7. Count how many words contain the letter ‘a’.', level: 'C5', completed: false },
      { id: 'p5-c5-8', title: '8. Capitalize the first letter of each word.', level: 'C5', completed: false },
      { id: 'p5-c5-9', title: '9. Print the sentence in title case (first letter capital, rest lowercase).', level: 'C5', completed: false },
      { id: 'p5-c5-10', title: '10. Remove extra spaces between words (normalize spacing).', level: 'C5', completed: false },
    ]
  },
  {
    id: 'phase-6',
    title: 'Phase 6 - Mixed Logical Challenges',
    description: 'Goal: Strengthen logical thinking with character manipulation.',
    questions: [
      // Category 1
      { id: 'p6-c1-1', title: '1. Print all numbers between 1 and N that are divisible by both 3 and 5.', level: 'C1', completed: false },
      { id: 'p6-c1-2', title: '2. Find the sum of digits of a number (use loop).', level: 'C1', completed: false },
      { id: 'p6-c1-3', title: '3. Check if a number is an Armstrong number.', level: 'C1', completed: false },
      { id: 'p6-c1-4', title: '4. Print all Armstrong numbers between 1 and 1000.', level: 'C1', completed: false },
      { id: 'p6-c1-5', title: '5. Find the factorial of a number using recursion.', level: 'C1', completed: false },
      { id: 'p6-c1-6', title: '6. Count how many even digits a number contains.', level: 'C1', completed: false },
      { id: 'p6-c1-7', title: '7. Print all prime numbers between 1 and N.', level: 'C1', completed: false },
      { id: 'p6-c1-8', title: '8. Print the reverse of a number (123 → 321).', level: 'C1', completed: false },
      { id: 'p6-c1-9', title: '9. Check if a number is palindrome (121 → true).', level: 'C1', completed: false },
      { id: 'p6-c1-10', title: '10. Check if a number is perfect (sum of factors equals number).', level: 'C1', completed: false },
      // Category 2
      { id: 'p6-c2-1', title: '1. Check if two strings are anagrams (without using collections).', level: 'C2', completed: false },
      { id: 'p6-c2-2', title: '2. Count vowels in each word of a sentence.', level: 'C2', completed: false },
      { id: 'p6-c2-3', title: '3. Reverse words in a string if their length is even.', level: 'C2', completed: false },
      { id: 'p6-c2-4', title: '4. Replace every vowel in a string with its position (a=1, e=2...).', level: 'C2', completed: false },
      { id: 'p6-c2-5', title: '5. Print characters that appear more than once (without map).', level: 'C2', completed: false },
      { id: 'p6-c2-6', title: '6. Count words that start and end with the same letter.', level: 'C2', completed: false },
      { id: 'p6-c2-7', title: '7. Toggle case for every alternate word in a sentence.', level: 'C2', completed: false },
      { id: 'p6-c2-8', title: '8. Check if two strings are rotations of each other.', level: 'C2', completed: false },
      { id: 'p6-c2-9', title: '9. Find the word with maximum vowels in a sentence.', level: 'C2', completed: false },
      { id: 'p6-c2-10', title: '10. Remove duplicate words from a sentence.', level: 'C2', completed: false },
      // Category 3
      { id: 'p6-c3-1', title: '1. Find the maximum and minimum element in an array.', level: 'C3', completed: false },
      { id: 'p6-c3-2', title: '2. Count how many many positive, negative, and zero elements are in an array.', level: 'C3', completed: false },
      { id: 'p6-c3-3', title: '3. Print all unique elements from an array.', level: 'C3', completed: false },
      { id: 'p6-c3-4', title: '4. Reverse an array in-place.', level: 'C3', completed: false },
      { id: 'p6-c3-5', title: '5. Shift all zeros to the end of the array.', level: 'C3', completed: false },
      { id: 'p6-c3-6', title: '6. Count how many elements are even at an even index.', level: 'C3', completed: false },
      { id: 'p6-c3-7', title: '7. Merge two arrays into one.', level: 'C3', completed: false },
      { id: 'p6-c3-8', title: '8. Find the second largest element in an array.', level: 'C3', completed: false },
      { id: 'p6-c3-9', title: '9. Rotate an array by one position to the right.', level: 'C3', completed: false },
      { id: 'p6-c3-10', title: '10. Find the sum of all elements at odd indices.', level: 'C3', completed: false },
      // Category 4
      { id: 'p6-c4-1', title: '1. Print a multiplication table in a formatted grid (10x10).', level: 'C4', completed: false },
      { id: 'p6-c4-2', title: '2. Print all pairs in an array whose sum equals a given number.', level: 'C4', completed: false },
      { id: 'p6-c4-3', title: '3. Print all subarrays of a given array.', level: 'C4', completed: false },
      { id: 'p6-c4-4', title: '4. Check if an array is sorted (ascending or descending).', level: 'C4', completed: false },
      { id: 'p6-c4-5', title: '5. Count how many times a number appears consecutively in an array.', level: 'C4', completed: false },
      { id: 'p6-c4-6', title: '6. Find all pairs of characters in a string that are the same (nested loop).', level: 'C4', completed: false },
      { id: 'p6-c4-7', title: '7. Print pattern of increasing characters (A, AB, ABC...).', level: 'C4', completed: false },
      { id: 'p6-c4-8', title: '8. Print Pascal’s triangle up to N rows.', level: 'C4', completed: false },
      { id: 'p6-c4-9', title: '9. Generate Fibonacci series up to N using recursion.', level: 'C4', completed: false },
      { id: 'p6-c4-10', title: '10. Print numbers in a spiral-like pattern (conceptual dry run).', level: 'C4', completed: false },
      // Category 5
      { id: 'p6-c5-1', title: '1. Given marks of students, find how many passed (>= 40).', level: 'C5', completed: false },
      { id: 'p6-c5-2', title: '2. Take age inputs and count how many are adults, minors, seniors.', level: 'C5', completed: false },
      { id: 'p6-c5-3', title: '3. Validate a password (at least one uppercase, lowercase, digit, special char).', level: 'C5', completed: false },
      { id: 'p6-c5-4', title: '4. Simulate a simple calculator using switch-case.', level: 'C5', completed: false },
      { id: 'p6-c5-5', title: '5. Count how many times a coin lands on heads/tails (use random).', level: 'C5', completed: false },
      { id: 'p6-c5-6', title: '6. Print frequency of each digit in a number.', level: 'C5', completed: false },
      { id: 'p6-c5-7', title: '7. Find common elements between two arrays.', level: 'C5', completed: false },
      { id: 'p6-c5-8', title: '8. Print characters that are common in two strings.', level: 'C5', completed: false },
      { id: 'p6-c5-9', title: '9. Count how many prime numbers are there in an array.', level: 'C5', completed: false },
      { id: 'p6-c5-10', title: '10. Print all palindromic words from a sentence.', level: 'C5', completed: false },
    ]
  }
];

export const SSC_CGL_SECTIONS = [
  { 
    id: 'ga', 
    title: 'General Awareness', 
    tasks: [
      'History: Ancient, Medieval, Modern', 
      'Indian Polity & Constitution', 
      'Geography: Indian & World', 
      'Economics: Macro & Micro', 
      'Physics', 
      'Chemistry', 
      'Biology', 
      'Computer Awareness', 
      'Static GK (Art, Culture, Awards)', 
      'Current Affairs (Last 12 Months)'
    ] 
  },
  { 
    id: 'english', 
    title: 'English Language', 
    tasks: [
      'Spotting Errors', 
      'Fill in the Blanks', 
      'Synonyms & Antonyms', 
      'Spelling Test', 
      'Idioms & Phrases', 
      'One Word Substitution', 
      'Sentence Improvement', 
      'Active/Passive Voice', 
      'Direct/Indirect Speech', 
      'Cloze Test', 
      'Reading Comprehension'
    ] 
  },
  { 
    id: 'reasoning', 
    title: 'General Intelligence & Reasoning', 
    tasks: [
      'Analogy (Verbal & Non-Verbal)', 
      'Classification', 
      'Series (Number & Alphabet)', 
      'Coding-Decoding', 
      'Blood Relations', 
      'Direction Sense', 
      'Ranking & Order', 
      'Venn Diagrams', 
      'Syllogism', 
      'Dice & Cubes', 
      'Mirror & Water Images', 
      'Paper Cutting & Folding', 
      'Embedded Figures', 
      'Matrix'
    ] 
  },
  { 
    id: 'quant', 
    title: 'Quantitative Aptitude', 
    tasks: [
      'Number System', 
      'LCM & HCF', 
      'Percentage', 
      'Profit, Loss & Discount', 
      'Simple & Compound Interest', 
      'Ratio & Proportion', 
      'Mixture & Alligation', 
      'Average', 
      'Time & Work', 
      'Pipe & Cistern', 
      'Time, Speed & Distance', 
      'Boat & Stream', 
      'Algebra', 
      'Geometry', 
      'Mensuration (2D & 3D)', 
      'Trigonometry', 
      'Data Interpretation (DI)'
    ] 
  }
];
